import { LearningModule } from '../types';

export const INITIAL_MODULES: LearningModule[] = [
  {
    id: '1',
    title: 'Climate-Smart Sahel Farming',
    instructor: 'Dr. Amina Bello (IITA)',
    thumbnail: '/stock/education.svg',
    lessonsCount: 12,
    category: 'Resilience',
    difficulty: 'Advanced',
    duration: '4h 15m',
    completed: false,
    description: 'Drought-tolerant varieties, conservation agriculture, and Zai pit techniques for the Sahel. Improve soil organic matter and water retention on sandy soils.',
    videoId: 'h2P5z2Q3yJ0',
    progress: 0,
    completedLessons: [],
  },
  {
    id: '2',
    title: 'Farm Finance in Volatile Markets',
    instructor: 'Chukwuma Eze (CBN Agric)',
    thumbnail: '/stock/education.svg',
    lessonsCount: 8,
    category: 'Economics',
    difficulty: 'Intermediate',
    duration: '2h 30m',
    completed: true,
    description: 'Navigating Naira volatility, input cost spikes, and cooperative bulk purchasing. Accessing NIRSAL credit and BOA loan windows for 2026 season.',
    videoId: 'Q6sL-7sF_Gw',
    progress: 100,
    completedLessons: [0, 1, 2, 3, 4, 5, 6, 7],
  },
  {
    id: '3',
    title: 'Precision Irrigation for Drylands',
    instructor: 'Prof. Issa Garba (ABU Zaria)',
    thumbnail: '/stock/education.svg',
    lessonsCount: 15,
    category: 'Tech',
    difficulty: 'Advanced',
    duration: '5h 00m',
    completed: false,
    description: 'Solar-powered drip irrigation, treadle pumps, and smart soil moisture sensors. Optimizing water usage under Sahel dry spell conditions.',
    videoId: '1s5o7s3y_wY',
    progress: 0,
    completedLessons: [],
  },
  {
    id: '4',
    title: 'Drone Scouting for Crop Health',
    instructor: 'Tech Lead Aisha (AgriMach NG)',
    thumbnail: '/stock/education.svg',
    lessonsCount: 6,
    category: 'Tech',
    difficulty: 'Beginner',
    duration: '1h 45m',
    completed: false,
    description: 'Deploy NDVI drones to detect Fall Armyworm and Striga stress early. Practical training for smallholder and medium-scale farms.',
    videoId: 'G9K7z9JcQj8',
    progress: 0,
    completedLessons: [],
  },
  {
    id: '5',
    title: 'Integrated Pest & Disease Management',
    instructor: 'Dr. Sunday Eze (IAR Samaru)',
    thumbnail: '/stock/education.svg',
    lessonsCount: 10,
    category: 'Resilience',
    difficulty: 'Intermediate',
    duration: '3h 20m',
    completed: false,
    description: 'Push-pull technology for FAW control, Striga management, pheromone traps, and cowpea intercropping. Reducing pesticide dependence across West Africa.',
    videoId: '6S6PJ8W1gbM',
    progress: 0,
    completedLessons: [],
  }
];